export const RECEIVE_ME = 'RECEIVE_ME';

export const FETCH_PEOPLE_BEGIN   = 'FETCH_PEOPLE_BEGIN';

export const FETCH_PEOPLE_SUCCESS = 'FETCH_PEOPLE_SUCCESS';

export const FETCH_PEOPLE_FAILURE = 'FETCH_PEOPLE_FAILURE';

export const PEOPLE_EMAIL_CHARS_BEGIN = 'PEOPLE_EMAIL_CHARS_BEGIN';

export const PEOPLE_EMAIL_CHARS_SUCCESS = 'PEOPLE_EMAIL_CHARS_SUCCESS';

export const PEOPLE_EMAIL_DUPS_BEGIN = 'PEOPLE_EMAIL_DUPS_BEGIN';

export const PEOPLE_EMAIL_DUPS_SUCCESS = 'PEOPLE_EMAIL_DUPS_SUCCESS';

